// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofwgmzfdgvazflqhkhfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9md2dtemZkZ3ZhemZscWhraGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDU5MzcsImV4cCI6MjA2OTA4MTkzN30.nH_7WI7MFobdO_ShqH8C_h1tunjaUKsBwWSisXN9MpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});